# Generated by Django 5.2.3 on 2025-07-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_remove_batch_depertment_batch_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'saturday')], default='sunday', max_length=500)),
                ('shift', models.CharField(choices=[('shift1', '9:00 AM - 10:25 AM'), ('shift2', '10:30 AM - 11:55 AM'), ('shift3', '12:00 PM to 01:25 PM'), ('shift4', '01:30 PM to 02:55 PM'), ('shift5', '03:00 PM to 04:25 PM'), ('shift6', '04:30 PM to 05:55 PM')], default='sunday', max_length=500)),
                ('course', models.CharField(max_length=500)),
                ('room', models.CharField(max_length=500)),
                ('faculty', models.CharField(max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.batch')),
                ('depertment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
    ]
