# Generated by Django 5.2.3 on 2025-07-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_routine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shedule',
            name='course',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='room',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='shift',
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift1_course',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift1_faculty',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift1_room',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift2_course',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift2_faculty',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift2_room',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift3_course',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift3_faculty',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift3_room',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift4_course',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift4_faculty',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift4_room',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift5_course',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift5_faculty',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift5_room',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift6_course',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift6_faculty',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shedule',
            name='shift6_room',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
