# Generated by Django 5.2.3 on 2025-07-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_routine', '0002_remove_shedule_course_remove_shedule_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='shift1_course',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift1_faculty',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Faculty details'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift1_room',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Romm no.'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift2_course',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift2_faculty',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Faculty details'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift2_room',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Romm no.'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift3_course',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift3_faculty',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Faculty details'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift3_room',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Romm no.'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift4_course',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift4_faculty',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Faculty details'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift4_room',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Romm no.'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift5_course',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift5_faculty',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Faculty details'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift5_room',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Romm no.'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift6_course',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift6_faculty',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Faculty details'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shift6_room',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Romm no.'),
        ),
    ]
