# Generated by Django 5.2.3 on 2025-07-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_routine', '0003_alter_shedule_shift1_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shedule',
            old_name='depertment',
            new_name='department',
        ),
    ]
